export const decorativeAssets = {
  aboutPolaroid: "/assets/decorative/about-polaroid.png",
  aboutNote: "/assets/decorative/about-note.png",
  coffeeCup: "/assets/decorative/coffee-cup.png",
  aboutDoodles: "/assets/decorative/about-doodles.png",
  aboutProbablyCoding: "/assets/decorative/about-probably-coding.png",
  aboutFuelDoodle: "/assets/decorative/about-fuel-doodle.png",
  alwaysLearning: "/assets/decorative/always-learning-doodle.png",
  heroDecorativeAssets: "/assets/decorative/hero-decorative-assets.png",
  heroGoodIdeas: "/assets/decorative/hero-good-ideas.png",
  heroStickyBuild: "/assets/decorative/hero-sticky-note-build.png",
  heroStickyBiggerThings: "/assets/decorative/hero-sticky-note-bigger-things.png",
  heroStars: "/assets/decorative/hero-stars.png",
  heroCodingDoodle: "/assets/decorative/hero-coding-doodle.png",
} as const;
